<?php
/**
 * @file
 * context_dri_object_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function context_dri_object_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-5yehNZCo1IglL3IekUfSppGGJxeUZDzP'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '5yehNZCo1IglL3IekUfSppGGJxeUZDzP',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'inspirezen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'inspirezen',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Subject',
    'visibility' => 0,
  );

  $export['facetapi-Y1FsEZkzYvvAxBXfJvqyaaxETF9ZuJ05'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Y1FsEZkzYvvAxBXfJvqyaaxETF9ZuJ05',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'inspirezen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'inspirezen',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Format',
    'visibility' => 0,
  );

  $export['facetapi-hVCQ3KtFFkSi4l0XTOjfJ0KdAYsfltPz'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'hVCQ3KtFFkSi4l0XTOjfJ0KdAYsfltPz',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'inspirezen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'inspirezen',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Era',
    'visibility' => 0,
  );

  $export['facetapi-l0FEMUxZ9XnDZV5Pv0CSBRXMs4Y1v576'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'l0FEMUxZ9XnDZV5Pv0CSBRXMs4Y1v576',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'inspirezen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'inspirezen',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-sl4W1X0POaR4LT1Jr0ul1DUKL3BZanNi'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sl4W1X0POaR4LT1Jr0ul1DUKL3BZanNi',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'inspirezen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'inspirezen',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Institution',
    'visibility' => 0,
  );

  return $export;
}
